// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eosxaoxnyzusshgsuime.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvc3hhb3hueXp1c3NoZ3N1aW1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NzIzOTQsImV4cCI6MjA2NDU0ODM5NH0.YTlUE3yiT5LKlZA_jbeNvMdQjMU3XzptI_Lrz5GLPXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);